### ISSUE TITLE
Misleading requirements.txt file, I think you deliberately did that.  

### ISSUE THREAD

**Issue by faisalnazik** [hlwarun/Sajilobook-Completed#1]
First of all this is a Django project, and the information about Django version is missing in requirements.txt file . Ahh if assume we assume that you push this repository about 4 months ago. And we install Django 3.0* or later , why we use the dependencies that only are used for the data science project and in this project there was not a single function was used regarding data science. 
I ran this project with following dependencies. And it's working fine. @hlwarun 

- asgiref==3.2.10
- certifi==2020.6.20
- chardet==3.0.4
- defusedxml==0.6.0
- dj-database-url==0.5.0
- Django==3.1.2
- django-allauth==0.42.0
- django-crispy-forms==1.9.2
- idna==2.10
- oauthlib==3.1.0
- Pillow==7.2.0
- psycopg2==2.8.6
- python-decouple==3.3
- python3-openid==3.2.0
- pytz==2020.1
- requests==2.24.0
- requests-oauthlib==1.3.0
- sqlparse==0.3.1
- urllib3==1.25.10
- whitenoise==5.2.0

**Comment by brittanibohnet** [comment]
@faisalnazik thank you for letting us know, I am new to Python and Django I was trying to install all of the listed dependencies and actually some of the versions are not existed written in orig requirements.txt .

**Comment by hlwarun** [comment]
> First of all this is a Django project, and the information about Django version is missing in requirements.txt file . Ahh if assume we assume that you push this repository about 4 months ago. And we install Django 3.0* or later , why we use the dependencies that only are used for the data science project and in this project there was not a single function was used regarding data science.
> I ran this project with following dependencies. And it's working fine. @hlwarun
> 
>     * asgiref==3.2.10
> 
>     * certifi==2020.6.20
> 
>     * chardet==3.0.4
> 
>     * defusedxml==0.6.0
> 
>     * dj-database-url==0.5.0
> 
>     * Django==3.1.2
> 
>     * django-allauth==0.42.0
> 
>     * django-crispy-forms==1.9.2
> 
>     * idna==2.10
> 
>     * oauthlib==3.1.0
> 
>     * Pillow==7.2.0
> 
>     * psycopg2==2.8.6
> 
>     * python-decouple==3.3
> 
>     * python3-openid==3.2.0
> 
>     * pytz==2020.1
> 
>     * requests==2.24.0
> 
>     * requests-oauthlib==1.3.0
> 
>     * sqlparse==0.3.1
> 
>     * urllib3==1.25.10
>

**Comment by hlwarun** [comment]
@faisalnazik thank you for your consideration. May be there was an issue with my virtual environment. And sorry for the inconvience created.
